all:
	cd ./lua && $(MAKE) linux
	cd ./sproto && $(MAKE)
	cd ./xls && $(MAKE)
	cd ./lua-seri && $(MAKE)
clean:
	cd ./lua && $(MAKE) clean
	cd ./sproto && $(MAKE) clean
	cd ./xls && $(MAKE) clean
	cd ./lua-seri && $(MAKE) clean
