all:
	cd ./skynet-src && $(MAKE)
	cd ./service_core-src && $(MAKE)
	cd ./lualib-src && $(MAKE)
clean:
	cd ./skynet-src && $(MAKE) clean
	cd ./service_core-src && $(MAKE) clean
	cd ./lualib-src && $(MAKE) clean
